In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/missing-impute/missing_impute.csv

In [2]:
import pandas as pd

df = pd.read_csv("/kaggle/input/missing-impute/missing_impute.csv")

In [3]:
df
# Here we can see id 6 and 8 has a null or missing  Age value
# we have to either remove it or fill that missing
# if there is minimum no of value missing and they donot harm the model performance we can remove them 
# else we have to fill those missing value

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

   id    city   age  married
0   1  lisbon  25.0        0
1   2  berlin  25.0        1
2   3  lisbon  30.0        1
3   4  lisbon  30.0        1
4   5  berlin  18.0        0
5   6  lisbon   NaN        0
6   7  berlin  30.0        1
7   8  berlin   NaN        0
8   9  berlin  25.0        1
9  10  madrid  25.0        1

In [4]:
age_col = df["age"]

In [5]:
age_col

0    25.0
1    25.0
2    30.0
3    30.0
4    18.0
5     NaN
6    30.0
7     NaN
8    25.0
9    25.0
Name: age, dtype: float64

In [7]:
import numpy as np
mean = np.mean(age_col)
mean

26.0

In [9]:
df["age"].fillna(mean)

0    25.0
1    25.0
2    30.0
3    30.0
4    18.0
5    26.0
6    30.0
7    26.0
8    25.0
9    25.0
Name: age, dtype: float64

In [11]:
df["age"]

0    25.0
1    25.0
2    30.0
3    30.0
4    18.0
5     NaN
6    30.0
7     NaN
8    25.0
9    25.0
Name: age, dtype: float64

In [12]:
df.isnull()

      id   city    age  married
0  False  False  False    False
1  False  False  False    False
2  False  False  False    False
3  False  False  False    False
4  False  False  False    False
5  False  False   True    False
6  False  False  False    False
7  False  False   True    False
8  False  False  False    False
9  False  False  False    False

In [13]:
df["age"].fillna(df["age"].mean())

0    25.0
1    25.0
2    30.0
3    30.0
4    18.0
5    26.0
6    30.0
7    26.0
8    25.0
9    25.0
Name: age, dtype: float64

In [14]:
df

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

   id    city   age  married
0   1  lisbon  25.0        0
1   2  berlin  25.0        1
2   3  lisbon  30.0        1
3   4  lisbon  30.0        1
4   5  berlin  18.0        0
5   6  lisbon   NaN        0
6   7  berlin  30.0        1
7   8  berlin   NaN        0
8   9  berlin  25.0        1
9  10  madrid  25.0        1

In [15]:
df['age'].fillna(df['age'].mean(),inplace=True)

In [16]:
df

   id    city   age  married
0   1  lisbon  25.0        0
1   2  berlin  25.0        1
2   3  lisbon  30.0        1
3   4  lisbon  30.0        1
4   5  berlin  18.0        0
5   6  lisbon  26.0        0
6   7  berlin  30.0        1
7   8  berlin  26.0        0
8   9  berlin  25.0        1
9  10  madrid  25.0        1